### ISSUE TITLE
PDF也传一份啊

### ISSUE THREAD

**Issue by JimAmuro** [alephO/Resume#1]
RT 看看效果学习下

**Comment by alephO** [comment]
哼，自己编译去！
（其实在这里，https://github.com/alephO/alephO.github.io/blob/master/Resume_JialongChen.pdf 这个模板有个小小的好处是可以自由用FA的图标）

**Comment by JimAmuro** [comment]
@alephO 可以 学到了

**Comment by JimAmuro** [comment]
@alephO 搜到原来的了，你为什么不fork？

**Comment by alephO** [comment]
@JimAmuro 我直接从shareLaTeX上自动同步过来的，之前在share LaTeX里放了好久
